version: 2
updates:
  # --- Python Dependencies ---
  - package-ecosystem: "pip"
    directory: "/"                    # Root directory where requirements.txt lives
    schedule:
      interval: "daily"               # Check for updates every day
    open-pull-requests-limit: 2       # Limit open PRs to avoid clutter
    target-branch: "main"             # Dependabot opens PRs to main
    commit-message:
      prefix: "deps(pip)"

  # --- GitHub Actions ---
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"                    # GitHub Actions are stored in .github/workflows
    schedule:
      interval: "daily"               # Check for updates daily
    open-pull-requests-limit: 2
    target-branch: "main"
    commit-message:
      prefix: "deps(actions)"