name: Django CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
      DEBUG: False

      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    

    steps:
    #Checkout code
    - name: Checkout code
      uses: actions/checkout@v6

    #Set up Python
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.11

    #Install dependencies (from Harmonet folder)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  # ensure coverage is installed

    #Set DJANGO_SETTINGS_MODULE environment variable
    - name: Set DJANGO_SETTINGS_MODULE
      run: echo "DJANGO_SETTINGS_MODULE=Harmonet.settings" >> $GITHUB_ENV

    #Run tests with coverage
    - name: Run tests with coverage
      run: |
        cd Harmonet
        coverage run manage.py test
        coverage report -m


